// <auto-generated />
using System;
using HR.Infrastructure.Persistence.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace HR.Infrastructure.Persistence.EntityFramework.Migrations
{
    [DbContext(typeof(HrDbContext))]
    internal sealed class HrDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("HR.Infrastructure.Security.Identity.ApplicationUser", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("AccessFailedCount")
                    .HasColumnType("int");

                b.Property<string>("ConcurrencyStamp")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("CustomerId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("nvarchar(64)")
                    .HasDefaultValue("demo-tenant");

                b.Property<string>("Email")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<bool>("EmailConfirmed")
                    .HasColumnType("bit");

                b.Property<bool>("LockoutEnabled")
                    .HasColumnType("bit");

                b.Property<DateTimeOffset?>("LockoutEnd")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("NormalizedEmail")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("NormalizedUserName")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("PasswordHash")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PhoneNumber")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("PhoneNumberConfirmed")
                    .HasColumnType("bit");

                b.Property<string>("SecurityStamp")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("TwoFactorEnabled")
                    .HasColumnType("bit");

                b.Property<string>("UserName")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.HasKey("Id");

                b.HasIndex("CustomerId");

                b.HasIndex("NormalizedEmail")
                    .HasDatabaseName("EmailIndex");

                b.HasIndex("NormalizedUserName")
                    .IsUnique()
                    .HasDatabaseName("UserNameIndex")
                    .HasFilter("[NormalizedUserName] IS NOT NULL");

                b.ToTable("AspNetUsers");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<Guid>", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("ConcurrencyStamp")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("NormalizedName")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.HasKey("Id");

                b.HasIndex("NormalizedName")
                    .IsUnique()
                    .HasDatabaseName("RoleNameIndex")
                    .HasFilter("[NormalizedName] IS NOT NULL");

                b.ToTable("AspNetRoles");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<Guid>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("ClaimType")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ClaimValue")
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("RoleId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("RoleId");

                b.ToTable("AspNetRoleClaims");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<Guid>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("ClaimType")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ClaimValue")
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("AspNetUserClaims");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<Guid>", b =>
            {
                b.Property<string>("LoginProvider")
                    .HasMaxLength(128)
                    .HasColumnType("nvarchar(128)");

                b.Property<string>("ProviderKey")
                    .HasMaxLength(128)
                    .HasColumnType("nvarchar(128)");

                b.Property<string>("ProviderDisplayName")
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("LoginProvider", "ProviderKey");

                b.HasIndex("UserId");

                b.ToTable("AspNetUserLogins");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<Guid>", b =>
            {
                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("RoleId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("UserId", "RoleId");

                b.HasIndex("RoleId");

                b.ToTable("AspNetUserRoles");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<Guid>", b =>
            {
                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("LoginProvider")
                    .HasMaxLength(128)
                    .HasColumnType("nvarchar(128)");

                b.Property<string>("Name")
                    .HasMaxLength(128)
                    .HasColumnType("nvarchar(128)");

                b.Property<string>("Value")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("UserId", "LoginProvider", "Name");

                b.ToTable("AspNetUserTokens");
            });

            modelBuilder.Entity("HR.Domain.Entities.AuditLog", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Action")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Actor")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("ActorEmail")
                    .HasMaxLength(320)
                    .HasColumnType("nvarchar(320)");

                b.Property<string>("Changes")
                    .HasMaxLength(4000)
                    .HasColumnType("nvarchar(4000)");

                b.Property<string>("CorrelationId")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<Guid?>("CustomerId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("EntityId")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("EntityName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<DateTimeOffset>("OccurredAtUtc")
                    .HasColumnType("datetimeoffset")
                    .HasDefaultValueSql("CURRENT_TIMESTAMP");

                b.Property<string>("Severity")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)")
                    .HasDefaultValue("Info");

                b.Property<string>("Source")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Metadata")
                    .HasMaxLength(2000)
                    .HasColumnType("nvarchar(2000)");

                b.HasKey("Id");

                b.HasIndex("CustomerId");

                b.HasIndex("OccurredAtUtc");

                b.ToTable("AuditLogs");
            });

            modelBuilder.Entity("HR.Domain.Entities.Customer", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("AddressLine1")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("AddressLine2")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("BillingEmail")
                    .HasMaxLength(320)
                    .HasColumnType("nvarchar(320)");

                b.Property<string>("BillingPhone")
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<string>("City")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Country")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("datetimeoffset")
                    .HasDefaultValueSql("CURRENT_TIMESTAMP");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("PostalCode")
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<string>("State")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)")
                    .HasDefaultValue("Active");

                b.Property<DateOnly?>("TrialEndsOn")
                    .HasColumnType("date");

                b.Property<DateTimeOffset?>("UpdatedAtUtc")
                    .HasColumnType("datetimeoffset");

                b.HasKey("Id");

                b.HasIndex("BillingEmail");

                b.ToTable("Customers");
            });

            modelBuilder.Entity("HR.Domain.Entities.Invoice", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<decimal>("AmountPaid")
                    .HasColumnType("decimal(18,2)");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("datetimeoffset")
                    .HasDefaultValueSql("CURRENT_TIMESTAMP");

                b.Property<Guid>("CustomerId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateOnly>("DueDate")
                    .HasColumnType("date");

                b.Property<DateOnly>("IssueDate")
                    .HasColumnType("date");

                b.Property<string>("InvoiceNumber")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Currency")
                    .IsRequired()
                    .HasMaxLength(3)
                    .HasColumnType("nvarchar(3)")
                    .HasDefaultValue("USD");

                b.Property<string>("Notes")
                    .HasMaxLength(1024)
                    .HasColumnType("nvarchar(1024)");

                b.Property<DateOnly?>("PaidDate")
                    .HasColumnType("date");

                b.Property<Guid?>("SubscriptionId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)")
                    .HasDefaultValue("Pending");

                b.Property<decimal>("Subtotal")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal>("TaxTotal")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal>("Total")
                    .HasColumnType("decimal(18,2)");

                b.Property<DateTimeOffset?>("UpdatedAtUtc")
                    .HasColumnType("datetimeoffset");

                b.HasKey("Id");

                b.HasIndex("CustomerId");

                b.HasIndex("InvoiceNumber")
                    .IsUnique();

                b.HasIndex("SubscriptionId");

                b.HasOne("HR.Domain.Entities.Customer", null)
                    .WithMany()
                    .HasForeignKey("CustomerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("HR.Domain.Entities.Subscription", null)
                    .WithMany()
                    .HasForeignKey("SubscriptionId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.ToTable("Invoices");
            });

            modelBuilder.Entity("HR.Domain.Entities.Organization", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .HasMaxLength(1024)
                    .HasColumnType("nvarchar(1024)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit")
                    .HasDefaultValue(true);

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<DateTime?>("UpdatedAtUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("Code")
                    .IsUnique();

                b.HasIndex("Name")
                    .IsUnique();

                b.ToTable("Organizations");

                b.HasData(
                    new
                    {
                        Id = new Guid("8d741596-7f48-4a44-9a9b-5d4d78f3dc9a"),
                        Code = "ACME",
                        CreatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                        Description = "Acme Corp demo organization",
                        IsActive = true,
                        Name = "Acme Corp"
                    });
            });

            modelBuilder.Entity("HR.Domain.Entities.Department", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Branch")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Code")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .HasMaxLength(1024)
                    .HasColumnType("nvarchar(1024)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit")
                    .HasDefaultValue(true);

                b.Property<int>("Level")
                    .HasColumnType("int")
                    .HasDefaultValue(0);

                b.Property<string>("Location")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<Guid?>("ManagerId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<Guid>("OrganizationId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Path")
                    .IsRequired()
                    .HasMaxLength(512)
                    .HasColumnType("nvarchar(512)");

                b.Property<Guid?>("ParentDepartmentId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("UpdatedAtUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("OrganizationId", "ParentDepartmentId", "Name")
                    .IsUnique();

                b.HasIndex("OrganizationId", "Code")
                    .IsUnique()
                    .HasFilter("[Code] IS NOT NULL AND [Code] <> ''");

                b.HasIndex("ParentDepartmentId");

                b.HasIndex("Path");

                b.ToTable("Departments");

                b.HasData(
                    new
                    {
                        Id = new Guid("5b0d38f7-8b37-4f33-9b77-39f8e8e5ef90"),
                        Branch = "Global",
                        Code = "HQ",
                        CreatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                        Description = "Corporate headquarters",
                        IsActive = true,
                        Level = 0,
                        Location = "New York",
                        Name = "Head Office",
                        OrganizationId = new Guid("8d741596-7f48-4a44-9a9b-5d4d78f3dc9a"),
                        Path = "/org/8d741596-7f48-4a44-9a9b-5d4d78f3dc9a/dept/5b0d38f7-8b37-4f33-9b77-39f8e8e5ef90"
                    },
                    new
                    {
                        Id = new Guid("2ff4b6f1-6f4e-4de0-85ed-2f1b83f6f0d8"),
                        Branch = "Product",
                        Code = "ENG",
                        CreatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                        Description = "Platform and application engineering",
                        IsActive = true,
                        Level = 1,
                        Location = "Seattle",
                        Name = "Engineering",
                        OrganizationId = new Guid("8d741596-7f48-4a44-9a9b-5d4d78f3dc9a"),
                        ParentDepartmentId = new Guid("5b0d38f7-8b37-4f33-9b77-39f8e8e5ef90"),
                        Path = "/org/8d741596-7f48-4a44-9a9b-5d4d78f3dc9a/dept/5b0d38f7-8b37-4f33-9b77-39f8e8e5ef90/2ff4b6f1-6f4e-4de0-85ed-2f1b83f6f0d8"
                    },
                    new
                    {
                        Id = new Guid("3c7d4f9a-0f8b-4f33-9ed9-6bff8e75b5f2"),
                        Branch = "Technology",
                        Code = "PLAT",
                        CreatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                        Description = "Platform services and infrastructure",
                        IsActive = true,
                        Level = 2,
                        Location = "Seattle",
                        Name = "Platform",
                        OrganizationId = new Guid("8d741596-7f48-4a44-9a9b-5d4d78f3dc9a"),
                        ParentDepartmentId = new Guid("2ff4b6f1-6f4e-4de0-85ed-2f1b83f6f0d8"),
                        Path = "/org/8d741596-7f48-4a44-9a9b-5d4d78f3dc9a/dept/5b0d38f7-8b37-4f33-9b77-39f8e8e5ef90/2ff4b6f1-6f4e-4de0-85ed-2f1b83f6f0d8/3c7d4f9a-0f8b-4f33-9ed9-6bff8e75b5f2"
                    },
                    new
                    {
                        Id = new Guid("13d7a3fd-91c0-44d3-9d63-7f53820f9bde"),
                        Branch = "Product",
                        Code = "APPS",
                        CreatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                        Description = "Customer-facing application development",
                        IsActive = true,
                        Level = 2,
                        Location = "Austin",
                        Name = "Applications",
                        OrganizationId = new Guid("8d741596-7f48-4a44-9a9b-5d4d78f3dc9a"),
                        ParentDepartmentId = new Guid("2ff4b6f1-6f4e-4de0-85ed-2f1b83f6f0d8"),
                        Path = "/org/8d741596-7f48-4a44-9a9b-5d4d78f3dc9a/dept/5b0d38f7-8b37-4f33-9b77-39f8e8e5ef90/2ff4b6f1-6f4e-4de0-85ed-2f1b83f6f0d8/13d7a3fd-91c0-44d3-9d63-7f53820f9bde"
                    },
                    new
                    {
                        Id = new Guid("dc05d230-9a87-4c5c-a8cf-1e1422ecf7b2"),
                        Branch = "Corporate",
                        Code = "HR",
                        CreatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                        Description = "People operations",
                        IsActive = true,
                        Level = 1,
                        Location = "New York",
                        Name = "HR",
                        OrganizationId = new Guid("8d741596-7f48-4a44-9a9b-5d4d78f3dc9a"),
                        ParentDepartmentId = new Guid("5b0d38f7-8b37-4f33-9b77-39f8e8e5ef90"),
                        Path = "/org/8d741596-7f48-4a44-9a9b-5d4d78f3dc9a/dept/5b0d38f7-8b37-4f33-9b77-39f8e8e5ef90/dc05d230-9a87-4c5c-a8cf-1e1422ecf7b2"
                    });
            });

            modelBuilder.Entity("HR.Domain.Entities.Employee", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("datetime2");

                b.Property<DateOnly?>("DateOfBirth")
                    .HasColumnType("date");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<DateOnly?>("EmploymentEndDate")
                    .HasColumnType("date");

                b.Property<DateOnly>("EmploymentStartDate")
                    .HasColumnType("date");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("JobArchitectureCareerTrack")
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<string>("JobArchitectureJobCode")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("JobArchitectureJobFamily")
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<string>("JobArchitectureJobFunction")
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<string>("JobArchitectureJobLevel")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("JobTitle")
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit")
                    .HasDefaultValue(true);

                b.HasKey("Id");

                b.ToTable("Employees");

                b.HasData(
                    new
                    {
                        Id = new Guid("df15d0d5-7b31-4a2c-924f-4da55b1fb677"),
                        CreatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                        Email = "alice.johnson@acme.test",
                        EmploymentStartDate = new DateOnly(2020, 1, 6),
                        FirstName = "Alice",
                        JobTitle = "Director of Engineering",
                        LastName = "Johnson"
                    },
                    new
                    {
                        Id = new Guid("dca9c1f7-5fbc-4c6c-8fd0-9be0384fe760"),
                        CreatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                        Email = "bob.smith@acme.test",
                        EmploymentStartDate = new DateOnly(2020, 4, 6),
                        FirstName = "Bob",
                        JobTitle = "Senior Platform Engineer",
                        LastName = "Smith"
                    },
                    new
                    {
                        Id = new Guid("c0d7683e-8e3d-4f6d-bf16-b0cb02f1455e"),
                        CreatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                        Email = "carol.lee@acme.test",
                        EmploymentStartDate = new DateOnly(2020, 7, 6),
                        FirstName = "Carol",
                        JobTitle = "Applications Lead",
                        LastName = "Lee"
                    },
                    new
                    {
                        Id = new Guid("0b90b2f9-2378-4e8f-9b77-4d56e0dcd8ec"),
                        CreatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                        Email = "david.patel@acme.test",
                        EmploymentStartDate = new DateOnly(2020, 3, 6),
                        FirstName = "David",
                        JobTitle = "HR Business Partner",
                        LastName = "Patel"
                    });
            });

            modelBuilder.Entity("HR.Domain.Entities.EmployeeDepartment", b =>
            {
                b.Property<Guid>("EmployeeId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("DepartmentId")
                    .HasColumnType("uniqueidentifier");

                b.Property<bool>("IsPrimary")
                    .HasColumnType("bit");

                b.HasKey("EmployeeId", "DepartmentId");

                b.HasIndex("DepartmentId");

                b.ToTable("EmployeeDepartments");

                b.HasData(
                    new
                    {
                        DepartmentId = new Guid("2ff4b6f1-6f4e-4de0-85ed-2f1b83f6f0d8"),
                        EmployeeId = new Guid("df15d0d5-7b31-4a2c-924f-4da55b1fb677"),
                        IsPrimary = true
                    },
                    new
                    {
                        DepartmentId = new Guid("3c7d4f9a-0f8b-4f33-9ed9-6bff8e75b5f2"),
                        EmployeeId = new Guid("df15d0d5-7b31-4a2c-924f-4da55b1fb677"),
                        IsPrimary = false
                    },
                    new
                    {
                        DepartmentId = new Guid("3c7d4f9a-0f8b-4f33-9ed9-6bff8e75b5f2"),
                        EmployeeId = new Guid("dca9c1f7-5fbc-4c6c-8fd0-9be0384fe760"),
                        IsPrimary = true
                    },
                    new
                    {
                        DepartmentId = new Guid("13d7a3fd-91c0-44d3-9d63-7f53820f9bde"),
                        EmployeeId = new Guid("dca9c1f7-5fbc-4c6c-8fd0-9be0384fe760"),
                        IsPrimary = false
                    },
                    new
                    {
                        DepartmentId = new Guid("13d7a3fd-91c0-44d3-9d63-7f53820f9bde"),
                        EmployeeId = new Guid("c0d7683e-8e3d-4f6d-bf16-b0cb02f1455e"),
                        IsPrimary = true
                    },
                    new
                    {
                        DepartmentId = new Guid("2ff4b6f1-6f4e-4de0-85ed-2f1b83f6f0d8"),
                        EmployeeId = new Guid("c0d7683e-8e3d-4f6d-bf16-b0cb02f1455e"),
                        IsPrimary = false
                    },
                    new
                    {
                        DepartmentId = new Guid("dc05d230-9a87-4c5c-a8cf-1e1422ecf7b2"),
                        EmployeeId = new Guid("0b90b2f9-2378-4e8f-9b77-4d56e0dcd8ec"),
                        IsPrimary = true
                    },
                    new
                    {
                        DepartmentId = new Guid("5b0d38f7-8b37-4f33-9b77-39f8e8e5ef90"),
                        EmployeeId = new Guid("0b90b2f9-2378-4e8f-9b77-4d56e0dcd8ec"),
                        IsPrimary = false
                    });
            });

            modelBuilder.Entity("HR.Domain.Entities.Subscription", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<bool>("AutoRenew")
                    .HasColumnType("bit")
                    .HasDefaultValue(true);

                b.Property<string>("BillingInterval")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<Guid>("CustomerId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Currency")
                    .IsRequired()
                    .HasMaxLength(3)
                    .HasColumnType("nvarchar(3)")
                    .HasDefaultValue("USD");

                b.Property<DateOnly?>("CancelledOn")
                    .HasColumnType("date");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("datetimeoffset")
                    .HasDefaultValueSql("CURRENT_TIMESTAMP");

                b.Property<DateOnly?>("EndDate")
                    .HasColumnType("date");

                b.Property<string>("PlanCode")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<decimal>("Price")
                    .HasColumnType("decimal(18,2)");

                b.Property<DateOnly?>("RenewalDate")
                    .HasColumnType("date");

                b.Property<DateOnly>("StartDate")
                    .HasColumnType("date");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)")
                    .HasDefaultValue("Active");

                b.Property<DateTimeOffset?>("UpdatedAtUtc")
                    .HasColumnType("datetimeoffset");

                b.HasKey("Id");

                b.HasIndex("CustomerId", "PlanCode");

                b.HasOne("HR.Domain.Entities.Customer", null)
                    .WithMany()
                    .HasForeignKey("CustomerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.ToTable("Subscriptions");
            });

            modelBuilder.Entity("HR.Domain.Entities.SubscriptionEntitlement", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<bool>("IsEnabled")
                    .HasColumnType("bit")
                    .HasDefaultValue(true);

                b.Property<string>("Description")
                    .HasMaxLength(512)
                    .HasColumnType("nvarchar(512)");

                b.Property<string>("DisplayName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("FeatureKey")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("nvarchar(120)");

                b.Property<string>("MeasurementUnit")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("PlanCode")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<int?>("Quantity")
                    .HasColumnType("int");

                b.Property<Guid?>("SubscriptionId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateOnly?>("EffectiveFrom")
                    .HasColumnType("date");

                b.Property<DateOnly?>("EffectiveTo")
                    .HasColumnType("date");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("datetimeoffset")
                    .HasDefaultValueSql("CURRENT_TIMESTAMP");

                b.HasKey("Id");

                b.HasIndex("SubscriptionId");

                b.HasIndex("PlanCode", "FeatureKey", "SubscriptionId");

                b.HasOne("HR.Domain.Entities.Subscription", null)
                    .WithMany()
                    .HasForeignKey("SubscriptionId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.ToTable("SubscriptionEntitlements");
            });

            modelBuilder.Entity("HR.Domain.Entities.UsageCounter", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<decimal>("CurrentValue")
                    .HasColumnType("decimal(18,4)");

                b.Property<string>("DisplayName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<DateTimeOffset>("LastResetAtUtc")
                    .HasColumnType("datetimeoffset")
                    .HasDefaultValueSql("CURRENT_TIMESTAMP");

                b.Property<decimal?>("Limit")
                    .HasColumnType("decimal(18,4)");

                b.Property<string>("MeasurementUnit")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("MetricKey")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("nvarchar(120)");

                b.Property<DateOnly>("PeriodEnd")
                    .HasColumnType("date");

                b.Property<DateOnly>("PeriodStart")
                    .HasColumnType("date");

                b.Property<Guid>("SubscriptionId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("UpdatedAtUtc")
                    .HasColumnType("datetimeoffset")
                    .HasDefaultValueSql("CURRENT_TIMESTAMP");

                b.HasKey("Id");

                b.HasIndex("SubscriptionId", "MetricKey", "PeriodStart", "PeriodEnd")
                    .IsUnique();

                b.HasOne("HR.Domain.Entities.Subscription", null)
                    .WithMany()
                    .HasForeignKey("SubscriptionId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.ToTable("UsageCounters");
            });

            modelBuilder.Entity("HR.Domain.Entities.Department", b =>
            {
                b.HasOne("HR.Domain.Entities.Organization", null)
                    .WithMany()
                    .HasForeignKey("OrganizationId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("HR.Domain.Entities.Department", null)
                    .WithMany()
                    .HasForeignKey("ParentDepartmentId")
                    .OnDelete(DeleteBehavior.Restrict);
            });

            modelBuilder.Entity("HR.Domain.Entities.EmployeeDepartment", b =>
            {
                b.HasOne("HR.Domain.Entities.Department", null)
                    .WithMany()
                    .HasForeignKey("DepartmentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("HR.Domain.Entities.Employee", null)
                    .WithMany()
                    .HasForeignKey("EmployeeId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<Guid>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<Guid>", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<Guid>", b =>
            {
                b.HasOne("HR.Infrastructure.Security.Identity.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<Guid>", b =>
            {
                b.HasOne("HR.Infrastructure.Security.Identity.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<Guid>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<Guid>", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("HR.Infrastructure.Security.Identity.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<Guid>", b =>
            {
                b.HasOne("HR.Infrastructure.Security.Identity.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

#pragma warning restore 612, 618
        }
    }
}
