// <auto-generated />
using System;
using HR.Infrastructure.Persistence.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace HR.Infrastructure.Persistence.EntityFramework.Migrations
{
    [DbContext(typeof(HrDbContext))]
    internal sealed class HrDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("HR.Domain.Entities.AuditLog", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Action")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Actor")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("ActorEmail")
                    .HasMaxLength(320)
                    .HasColumnType("nvarchar(320)");

                b.Property<string>("Changes")
                    .HasMaxLength(4000)
                    .HasColumnType("nvarchar(4000)");

                b.Property<string>("CorrelationId")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<Guid?>("CustomerId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("EntityId")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("EntityName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<DateTimeOffset>("OccurredAtUtc")
                    .HasColumnType("datetimeoffset")
                    .HasDefaultValueSql("CURRENT_TIMESTAMP");

                b.Property<string>("Severity")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)")
                    .HasDefaultValue("Info");

                b.Property<string>("Source")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Metadata")
                    .HasMaxLength(2000)
                    .HasColumnType("nvarchar(2000)");

                b.HasKey("Id");

                b.HasIndex("CustomerId");

                b.HasIndex("OccurredAtUtc");

                b.ToTable("AuditLogs");
            });

            modelBuilder.Entity("HR.Domain.Entities.Customer", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("AddressLine1")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("AddressLine2")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("BillingEmail")
                    .HasMaxLength(320)
                    .HasColumnType("nvarchar(320)");

                b.Property<string>("BillingPhone")
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<string>("City")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Country")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("datetimeoffset")
                    .HasDefaultValueSql("CURRENT_TIMESTAMP");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("PostalCode")
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<string>("State")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)")
                    .HasDefaultValue("Active");

                b.Property<DateOnly?>("TrialEndsOn")
                    .HasColumnType("date");

                b.Property<DateTimeOffset?>("UpdatedAtUtc")
                    .HasColumnType("datetimeoffset");

                b.HasKey("Id");

                b.HasIndex("BillingEmail");

                b.ToTable("Customers");
            });

            modelBuilder.Entity("HR.Domain.Entities.Invoice", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<decimal>("AmountPaid")
                    .HasColumnType("decimal(18,2)");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("datetimeoffset")
                    .HasDefaultValueSql("CURRENT_TIMESTAMP");

                b.Property<Guid>("CustomerId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateOnly>("DueDate")
                    .HasColumnType("date");

                b.Property<DateOnly>("IssueDate")
                    .HasColumnType("date");

                b.Property<string>("InvoiceNumber")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Currency")
                    .IsRequired()
                    .HasMaxLength(3)
                    .HasColumnType("nvarchar(3)")
                    .HasDefaultValue("USD");

                b.Property<string>("Notes")
                    .HasMaxLength(1024)
                    .HasColumnType("nvarchar(1024)");

                b.Property<DateOnly?>("PaidDate")
                    .HasColumnType("date");

                b.Property<Guid?>("SubscriptionId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)")
                    .HasDefaultValue("Pending");

                b.Property<decimal>("Subtotal")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal>("TaxTotal")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal>("Total")
                    .HasColumnType("decimal(18,2)");

                b.Property<DateTimeOffset?>("UpdatedAtUtc")
                    .HasColumnType("datetimeoffset");

                b.HasKey("Id");

                b.HasIndex("CustomerId");

                b.HasIndex("InvoiceNumber")
                    .IsUnique();

                b.HasIndex("SubscriptionId");

                b.HasOne("HR.Domain.Entities.Customer", null)
                    .WithMany()
                    .HasForeignKey("CustomerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("HR.Domain.Entities.Subscription", null)
                    .WithMany()
                    .HasForeignKey("SubscriptionId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.ToTable("Invoices");
            });

            modelBuilder.Entity("HR.Domain.Entities.Subscription", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<bool>("AutoRenew")
                    .HasColumnType("bit")
                    .HasDefaultValue(true);

                b.Property<string>("BillingInterval")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<Guid>("CustomerId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Currency")
                    .IsRequired()
                    .HasMaxLength(3)
                    .HasColumnType("nvarchar(3)")
                    .HasDefaultValue("USD");

                b.Property<DateOnly?>("CancelledOn")
                    .HasColumnType("date");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("datetimeoffset")
                    .HasDefaultValueSql("CURRENT_TIMESTAMP");

                b.Property<DateOnly?>("EndDate")
                    .HasColumnType("date");

                b.Property<string>("PlanCode")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<decimal>("Price")
                    .HasColumnType("decimal(18,2)");

                b.Property<DateOnly?>("RenewalDate")
                    .HasColumnType("date");

                b.Property<DateOnly>("StartDate")
                    .HasColumnType("date");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)")
                    .HasDefaultValue("Active");

                b.Property<DateTimeOffset?>("UpdatedAtUtc")
                    .HasColumnType("datetimeoffset");

                b.HasKey("Id");

                b.HasIndex("CustomerId", "PlanCode");

                b.HasOne("HR.Domain.Entities.Customer", null)
                    .WithMany()
                    .HasForeignKey("CustomerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.ToTable("Subscriptions");
            });

            modelBuilder.Entity("HR.Domain.Entities.SubscriptionEntitlement", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<bool>("IsEnabled")
                    .HasColumnType("bit")
                    .HasDefaultValue(true);

                b.Property<string>("Description")
                    .HasMaxLength(512)
                    .HasColumnType("nvarchar(512)");

                b.Property<string>("DisplayName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("FeatureKey")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("nvarchar(120)");

                b.Property<string>("MeasurementUnit")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("PlanCode")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<int?>("Quantity")
                    .HasColumnType("int");

                b.Property<Guid?>("SubscriptionId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateOnly?>("EffectiveFrom")
                    .HasColumnType("date");

                b.Property<DateOnly?>("EffectiveTo")
                    .HasColumnType("date");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("datetimeoffset")
                    .HasDefaultValueSql("CURRENT_TIMESTAMP");

                b.HasKey("Id");

                b.HasIndex("SubscriptionId");

                b.HasIndex("PlanCode", "FeatureKey", "SubscriptionId");

                b.HasOne("HR.Domain.Entities.Subscription", null)
                    .WithMany()
                    .HasForeignKey("SubscriptionId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.ToTable("SubscriptionEntitlements");
            });

            modelBuilder.Entity("HR.Domain.Entities.UsageCounter", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<decimal>("CurrentValue")
                    .HasColumnType("decimal(18,4)");

                b.Property<string>("DisplayName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<DateTimeOffset>("LastResetAtUtc")
                    .HasColumnType("datetimeoffset")
                    .HasDefaultValueSql("CURRENT_TIMESTAMP");

                b.Property<decimal?>("Limit")
                    .HasColumnType("decimal(18,4)");

                b.Property<string>("MeasurementUnit")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("MetricKey")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("nvarchar(120)");

                b.Property<DateOnly>("PeriodEnd")
                    .HasColumnType("date");

                b.Property<DateOnly>("PeriodStart")
                    .HasColumnType("date");

                b.Property<Guid>("SubscriptionId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("UpdatedAtUtc")
                    .HasColumnType("datetimeoffset")
                    .HasDefaultValueSql("CURRENT_TIMESTAMP");

                b.HasKey("Id");

                b.HasIndex("SubscriptionId", "MetricKey", "PeriodStart", "PeriodEnd")
                    .IsUnique();

                b.HasOne("HR.Domain.Entities.Subscription", null)
                    .WithMany()
                    .HasForeignKey("SubscriptionId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.ToTable("UsageCounters");
            });

#pragma warning restore 612, 618
        }
    }
}
