// <auto-generated />
using System;
using HR.Infrastructure.Persistence.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace HR.Infrastructure.Persistence.EntityFramework.Migrations
{
    [DbContext(typeof(HrDbContext))]
    internal sealed class HrDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("HR.Infrastructure.Security.Identity.ApplicationUser", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("AccessFailedCount")
                    .HasColumnType("int");

                b.Property<string>("ConcurrencyStamp")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("CustomerId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("nvarchar(64)")
                    .HasDefaultValue("demo-tenant");

                b.Property<string>("Email")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<bool>("EmailConfirmed")
                    .HasColumnType("bit");

                b.Property<bool>("LockoutEnabled")
                    .HasColumnType("bit");

                b.Property<DateTimeOffset?>("LockoutEnd")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("NormalizedEmail")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("NormalizedUserName")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("PasswordHash")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PhoneNumber")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("PhoneNumberConfirmed")
                    .HasColumnType("bit");

                b.Property<string>("SecurityStamp")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("TwoFactorEnabled")
                    .HasColumnType("bit");

                b.Property<string>("UserName")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.HasKey("Id");

                b.HasIndex("CustomerId");

                b.HasIndex("NormalizedEmail")
                    .HasDatabaseName("EmailIndex");

                b.HasIndex("NormalizedUserName")
                    .IsUnique()
                    .HasDatabaseName("UserNameIndex")
                    .HasFilter("[NormalizedUserName] IS NOT NULL");

                b.ToTable("AspNetUsers");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<Guid>", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("ConcurrencyStamp")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("NormalizedName")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.HasKey("Id");

                b.HasIndex("NormalizedName")
                    .IsUnique()
                    .HasDatabaseName("RoleNameIndex")
                    .HasFilter("[NormalizedName] IS NOT NULL");

                b.ToTable("AspNetRoles");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<Guid>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("ClaimType")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ClaimValue")
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("RoleId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("RoleId");

                b.ToTable("AspNetRoleClaims");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<Guid>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("ClaimType")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ClaimValue")
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("AspNetUserClaims");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<Guid>", b =>
            {
                b.Property<string>("LoginProvider")
                    .HasMaxLength(128)
                    .HasColumnType("nvarchar(128)");

                b.Property<string>("ProviderKey")
                    .HasMaxLength(128)
                    .HasColumnType("nvarchar(128)");

                b.Property<string>("ProviderDisplayName")
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("LoginProvider", "ProviderKey");

                b.HasIndex("UserId");

                b.ToTable("AspNetUserLogins");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<Guid>", b =>
            {
                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("RoleId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("UserId", "RoleId");

                b.HasIndex("RoleId");

                b.ToTable("AspNetUserRoles");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<Guid>", b =>
            {
                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("LoginProvider")
                    .HasMaxLength(128)
                    .HasColumnType("nvarchar(128)");

                b.Property<string>("Name")
                    .HasMaxLength(128)
                    .HasColumnType("nvarchar(128)");

                b.Property<string>("Value")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("UserId", "LoginProvider", "Name");

                b.ToTable("AspNetUserTokens");
            });

            modelBuilder.Entity("HR.Domain.Entities.AuditLog", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Action")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Actor")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("ActorEmail")
                    .HasMaxLength(320)
                    .HasColumnType("nvarchar(320)");

                b.Property<string>("Changes")
                    .HasMaxLength(4000)
                    .HasColumnType("nvarchar(4000)");

                b.Property<string>("CorrelationId")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<Guid?>("CustomerId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("EntityId")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("EntityName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<DateTimeOffset>("OccurredAtUtc")
                    .HasColumnType("datetimeoffset")
                    .HasDefaultValueSql("CURRENT_TIMESTAMP");

                b.Property<string>("Severity")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)")
                    .HasDefaultValue("Info");

                b.Property<string>("Source")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Metadata")
                    .HasMaxLength(2000)
                    .HasColumnType("nvarchar(2000)");

                b.HasKey("Id");

                b.HasIndex("CustomerId");

                b.HasIndex("OccurredAtUtc");

                b.ToTable("AuditLogs");
            });

            modelBuilder.Entity("HR.Domain.Entities.Customer", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("AddressLine1")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("AddressLine2")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("BillingEmail")
                    .HasMaxLength(320)
                    .HasColumnType("nvarchar(320)");

                b.Property<string>("BillingPhone")
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<string>("City")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Country")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("datetimeoffset")
                    .HasDefaultValueSql("CURRENT_TIMESTAMP");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("PostalCode")
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<string>("State")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)")
                    .HasDefaultValue("Active");

                b.Property<DateOnly?>("TrialEndsOn")
                    .HasColumnType("date");

                b.Property<DateTimeOffset?>("UpdatedAtUtc")
                    .HasColumnType("datetimeoffset");

                b.HasKey("Id");

                b.HasIndex("BillingEmail");

                b.ToTable("Customers");
            });

            modelBuilder.Entity("HR.Domain.Entities.Invoice", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<decimal>("AmountPaid")
                    .HasColumnType("decimal(18,2)");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("datetimeoffset")
                    .HasDefaultValueSql("CURRENT_TIMESTAMP");

                b.Property<Guid>("CustomerId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateOnly>("DueDate")
                    .HasColumnType("date");

                b.Property<DateOnly>("IssueDate")
                    .HasColumnType("date");

                b.Property<string>("InvoiceNumber")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Currency")
                    .IsRequired()
                    .HasMaxLength(3)
                    .HasColumnType("nvarchar(3)")
                    .HasDefaultValue("USD");

                b.Property<string>("Notes")
                    .HasMaxLength(1024)
                    .HasColumnType("nvarchar(1024)");

                b.Property<DateOnly?>("PaidDate")
                    .HasColumnType("date");

                b.Property<Guid?>("SubscriptionId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)")
                    .HasDefaultValue("Pending");

                b.Property<decimal>("Subtotal")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal>("TaxTotal")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal>("Total")
                    .HasColumnType("decimal(18,2)");

                b.Property<DateTimeOffset?>("UpdatedAtUtc")
                    .HasColumnType("datetimeoffset");

                b.HasKey("Id");

                b.HasIndex("CustomerId");

                b.HasIndex("InvoiceNumber")
                    .IsUnique();

                b.HasIndex("SubscriptionId");

                b.HasOne("HR.Domain.Entities.Customer", null)
                    .WithMany()
                    .HasForeignKey("CustomerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("HR.Domain.Entities.Subscription", null)
                    .WithMany()
                    .HasForeignKey("SubscriptionId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.ToTable("Invoices");
            });

            modelBuilder.Entity("HR.Domain.Entities.Organization", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Description")
                    .HasMaxLength(1024)
                    .HasColumnType("nvarchar(1024)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit")
                    .HasDefaultValue(true);

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.HasKey("Id");

                b.HasIndex("Code")
                    .IsUnique();

                b.ToTable("Organizations");
            });

            modelBuilder.Entity("HR.Domain.Entities.Department", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Branch")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Description")
                    .HasMaxLength(1024)
                    .HasColumnType("nvarchar(1024)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit")
                    .HasDefaultValue(true);

                b.Property<string>("Location")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<Guid?>("ManagerId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<Guid>("OrganizationId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("ParentDepartmentId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("OrganizationId", "Code")
                    .IsUnique();

                b.HasIndex("ParentDepartmentId");

                b.ToTable("Departments");
            });

            modelBuilder.Entity("HR.Domain.Entities.Employee", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateOnly?>("DateOfBirth")
                    .HasColumnType("date");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<DateOnly?>("EmploymentEndDate")
                    .HasColumnType("date");

                b.Property<DateOnly>("EmploymentStartDate")
                    .HasColumnType("date");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("JobArchitectureCareerTrack")
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<string>("JobArchitectureJobCode")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("JobArchitectureJobFamily")
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<string>("JobArchitectureJobFunction")
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<string>("JobArchitectureJobLevel")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("JobTitle")
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.HasKey("Id");

                b.ToTable("Employees");
            });

            modelBuilder.Entity("HR.Domain.Entities.EmployeeDepartment", b =>
            {
                b.Property<Guid>("EmployeeId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("DepartmentId")
                    .HasColumnType("uniqueidentifier");

                b.Property<bool>("IsPrimary")
                    .HasColumnType("bit");

                b.HasKey("EmployeeId", "DepartmentId");

                b.HasIndex("DepartmentId");

                b.ToTable("EmployeeDepartments");
            });

            modelBuilder.Entity("HR.Domain.Entities.Subscription", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<bool>("AutoRenew")
                    .HasColumnType("bit")
                    .HasDefaultValue(true);

                b.Property<string>("BillingInterval")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<Guid>("CustomerId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Currency")
                    .IsRequired()
                    .HasMaxLength(3)
                    .HasColumnType("nvarchar(3)")
                    .HasDefaultValue("USD");

                b.Property<DateOnly?>("CancelledOn")
                    .HasColumnType("date");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("datetimeoffset")
                    .HasDefaultValueSql("CURRENT_TIMESTAMP");

                b.Property<DateOnly?>("EndDate")
                    .HasColumnType("date");

                b.Property<string>("PlanCode")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<decimal>("Price")
                    .HasColumnType("decimal(18,2)");

                b.Property<DateOnly?>("RenewalDate")
                    .HasColumnType("date");

                b.Property<DateOnly>("StartDate")
                    .HasColumnType("date");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)")
                    .HasDefaultValue("Active");

                b.Property<DateTimeOffset?>("UpdatedAtUtc")
                    .HasColumnType("datetimeoffset");

                b.HasKey("Id");

                b.HasIndex("CustomerId", "PlanCode");

                b.HasOne("HR.Domain.Entities.Customer", null)
                    .WithMany()
                    .HasForeignKey("CustomerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.ToTable("Subscriptions");
            });

            modelBuilder.Entity("HR.Domain.Entities.SubscriptionEntitlement", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<bool>("IsEnabled")
                    .HasColumnType("bit")
                    .HasDefaultValue(true);

                b.Property<string>("Description")
                    .HasMaxLength(512)
                    .HasColumnType("nvarchar(512)");

                b.Property<string>("DisplayName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("FeatureKey")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("nvarchar(120)");

                b.Property<string>("MeasurementUnit")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("PlanCode")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<int?>("Quantity")
                    .HasColumnType("int");

                b.Property<Guid?>("SubscriptionId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateOnly?>("EffectiveFrom")
                    .HasColumnType("date");

                b.Property<DateOnly?>("EffectiveTo")
                    .HasColumnType("date");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("datetimeoffset")
                    .HasDefaultValueSql("CURRENT_TIMESTAMP");

                b.HasKey("Id");

                b.HasIndex("SubscriptionId");

                b.HasIndex("PlanCode", "FeatureKey", "SubscriptionId");

                b.HasOne("HR.Domain.Entities.Subscription", null)
                    .WithMany()
                    .HasForeignKey("SubscriptionId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.ToTable("SubscriptionEntitlements");
            });

            modelBuilder.Entity("HR.Domain.Entities.UsageCounter", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<decimal>("CurrentValue")
                    .HasColumnType("decimal(18,4)");

                b.Property<string>("DisplayName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<DateTimeOffset>("LastResetAtUtc")
                    .HasColumnType("datetimeoffset")
                    .HasDefaultValueSql("CURRENT_TIMESTAMP");

                b.Property<decimal?>("Limit")
                    .HasColumnType("decimal(18,4)");

                b.Property<string>("MeasurementUnit")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("MetricKey")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("nvarchar(120)");

                b.Property<DateOnly>("PeriodEnd")
                    .HasColumnType("date");

                b.Property<DateOnly>("PeriodStart")
                    .HasColumnType("date");

                b.Property<Guid>("SubscriptionId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("UpdatedAtUtc")
                    .HasColumnType("datetimeoffset")
                    .HasDefaultValueSql("CURRENT_TIMESTAMP");

                b.HasKey("Id");

                b.HasIndex("SubscriptionId", "MetricKey", "PeriodStart", "PeriodEnd")
                    .IsUnique();

                b.HasOne("HR.Domain.Entities.Subscription", null)
                    .WithMany()
                    .HasForeignKey("SubscriptionId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.ToTable("UsageCounters");
            });

            modelBuilder.Entity("HR.Domain.Entities.Department", b =>
            {
                b.HasOne("HR.Domain.Entities.Organization", null)
                    .WithMany()
                    .HasForeignKey("OrganizationId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("HR.Domain.Entities.Department", null)
                    .WithMany()
                    .HasForeignKey("ParentDepartmentId")
                    .OnDelete(DeleteBehavior.Restrict);
            });

            modelBuilder.Entity("HR.Domain.Entities.EmployeeDepartment", b =>
            {
                b.HasOne("HR.Domain.Entities.Department", null)
                    .WithMany()
                    .HasForeignKey("DepartmentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("HR.Domain.Entities.Employee", null)
                    .WithMany()
                    .HasForeignKey("EmployeeId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<Guid>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<Guid>", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<Guid>", b =>
            {
                b.HasOne("HR.Infrastructure.Security.Identity.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<Guid>", b =>
            {
                b.HasOne("HR.Infrastructure.Security.Identity.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<Guid>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<Guid>", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("HR.Infrastructure.Security.Identity.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<Guid>", b =>
            {
                b.HasOne("HR.Infrastructure.Security.Identity.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

#pragma warning restore 612, 618
        }
    }
}
